import product_1 from '../img/products/product-1.png'
import product_2 from '../img/products/product-2.png'
import product_3 from '../img/products/product-3.png'
import product_4 from '../img/products/product-4.png'
import product_5 from '../img/products/product-5.png'
import product_6 from '../img/products/product-6.png'
import product_7 from '../img/products/product-7.png'
import product_8 from '../img/products/product-8.png'


export const dummyProducts: any[] = [
    {
        id: 1,
        slug: 'product-1',
        image:`${product_1}`,
        price: 1800,
        title: 'Nike-1',
        description: 'Кроссовки отличного качества...',
        newModel: true,
        brend: 'nike',
        quantity: 0,
    },
    {
        id: 2,
        slug: 'product-2',
        image:`${product_2}`,
        price: 2000,
        title: 'Nike-2',
        description: 'Кроссовки отличного качества...',
        brend: 'adidas',
        quantity: 0,
    },
    {
        id: 3,
        slug: 'product-3',
        image:`${product_3}`,
        price: 3800,
        title: 'Nike-3',
        description: 'Кроссовки отличного качества...',
        newModel: true,
        brend: 'newbalance',
        quantity: 0,
    },
    {
        id: 4,
        slug: 'product-4',
        image:`${product_4}`,
        price: 4800,
        title: 'Nike-4',
        description: 'Кроссовки отличного качества...',
        newModel: true,
        brend: 'puma',
        quantity: 0,
    },
    {
        id: 5,
        slug: 'product-5',
        image:`${product_5}`,
        price: 5800,
        title: 'Nike-5',
        description: 'Кроссовки отличного качества...',
        brend: 'converse',
        quantity: 0,
    },
    {
        id: 6,
        slug: 'product-6',
        image:`${product_6}`,
        price: 6800,
        title: 'Nike-6',
        description: 'Кроссовки отличного качества...',
        brend: 'reebok',
        quantity: 0,
    },
    {
        id: 7,
        slug: 'product-7',
        image:`${product_7}`,
        price: 7800,
        title: 'Nike-7',
        description: 'Кроссовки отличного качества...',
        brend: 'nike',
        quantity: 0,
    },
    {
        id: 8,
        slug: 'product-8',
        image:`${product_8}`,
        price: 7800,
        title: 'Nike-8',
        description: 'Кроссовки отличного качества...',
        brend: 'adidas',
        quantity: 0,
    },
    {
        id: 9,
        slug: 'product-9',
        image:`${product_1}`,
        price: 7800,
        title: 'Nike9',
        description: 'Кроссовки отличного качества...',
        newModel: true,
        brend: 'reebok',
        quantity: 0,
    },
    {
        id: 10,
        slug: 'product-10',
        image:`${product_5}`,
        price: 7800,
        title: 'Nike10',
        description: 'Кроссовки отличного качества...',
        brend: 'converse',
        newModel: true,
        quantity: 0,
    },
    {
        id: 11,
        slug: 'product-11',
        image:`${product_3}`,
        price: 7800,
        title: 'Nike11',
        description: 'Кроссовки отличного качества...',
        brend: 'adidas',
        quantity: 0,
    },
    {
        id: 12,
        slug: 'product-12',
        image:`${product_2}`,
        price: 7800,
        title: 'Nike12',
        description: 'Кроссовки отличного качества...',
        brend: 'nike',
        newModel: true,
        quantity: 0,
    },
    {
        id: 13,
        slug: 'product-13',
        image:`${product_4}`,
        price: 7800,
        title: 'Nike13',
        description: 'Кроссовки отличного качества...',
        brend: 'newbalance',
        quantity: 0,
    },
    {
        id: 14,
        slug: 'product-14',
        image:`${product_6}`,
        price: 7800,
        title: 'Nike14',
        description: 'Кроссовки отличного качества...',
        brend: 'adidas',
        quantity: 0,
    },
    {
        id: 15,
        slug: 'product-15',
        image:`${product_7}`,
        price: 7800,
        title: 'Nike15',
        description: 'Кроссовки отличного качества...',
        brend: 'newbalance',
        newModel: true,
        quantity: 0,
    },
    // {
    //     id: 16,
    //     slug: 'product-16',
    //     image:`${product_8}`,
    //     price: 7800,
    //     title: 'Nike',
    //     description: 'Кроссовки отличного качества...',
    //     brend: 'converse',
    //     newModel: true,
    // },
    // {
    //     id: 17,
    //     slug: 'product-17',
    //     image:`${product_5}`,
    //     price: 7800,
    //     title: 'Nike',
    //     description: 'Кроссовки отличного качества...',
    //     brend: 'reebok',
    //     newModel: true,
    // },
    // {
    //     id: 18,
    //     slug: 'product-18',
    //     image:`${product_4}`,
    //     price: 7800,
    //     title: 'Nike',
    //     description: 'Кроссовки отличного качества...',
    //     brend: 'nike',
    //     newModel: true,
    // },
]